# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "billomat-rb"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ronald Becher"]
  s.date = "2012-04-14"
  s.description = "A neat ruby library for interacting with the RESTfull API of billomat"
  s.email = "rb@ronald-becher.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "CHANGES.textile",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "TODO.textile",
    "VERSION.yml",
    "billomat-rb.gemspec",
    "lib/billomat-rb.rb",
    "lib/billomat/clients.rb",
    "lib/billomat/myself.rb",
    "lib/billomat/settings.rb",
    "lib/billomat/unit.rb",
    "lib/billomat/users.rb"
  ]
  s.homepage = "http://github.com/rbecher/billomat-rb"
  s.require_paths = ["lib"]
  s.rubyforge_project = "billomat-rb"
  s.rubygems_version = "1.8.21"
  s.summary = "Ruby library for interacting with the RESTfull billomat api."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.2.3"])
      s.add_runtime_dependency(%q<activeresource>, [">= 3.2.3"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.2.3"])
      s.add_dependency(%q<activeresource>, [">= 3.2.3"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.2.3"])
    s.add_dependency(%q<activeresource>, [">= 3.2.3"])
  end
end

